OmniResources.FansOfFuryPublicWeb/OmniResources.FansOfFuryPublicWeb.Mvc/Models/QrCode/SurveyResponseViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using AutoMapper;
using Foolproof;
using OmniResources.FansOfFuryPublicWeb.Data.Table;

namespace OmniResources.FansOfFuryPublicWeb.Mvc.Models.QrCode
{
    public class SurveyResponseViewModel
    {
        static SurveyResponseViewModel()
        {
            Mapper.CreateMap<SurveyResponseViewModel, SurveyResponse>().ReverseMap();
            Mapper.CreateMap<SurveyResponseViewModel, UserData>().ReverseMap();
        }

        /// <summary>
        /// Gets or sets the first naame of the user
        /// </summary>
        [Required, DisplayName("First Name")]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or sets the last name of the user
        /// </summary>
        [Required, DisplayName("Last Name")]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or sets the email address of the user
        /// </summary>
        [Required, EmailAddress, DisplayName("Email Address")]
        public string EmailAddress { get; set; }

        /// <summary>
        /// Gets or sets the name to display for the user on the scoreboard
        /// </summary>
        [DisplayName("Scoreboard Name")]
        public string ScoreboardName { get; set; }

        /// <summary>
        /// Gets or sets a password for the user that they must enter if they want to have their name on the scoreboard
        /// </summary>
        [RequiredIfNotEmpty("ScoreboardName")]
        public string Password { get; set; }

        [RequiredIfNotEmpty("ScoreboardName"), Compare("Password"), DisplayName("Confirm Password")]
        public string ConfirmPassword { get; set; }
    }
}

OmniResources.FansOfFuryPublicWeb/OmniResources.FansOfFuryPublicWeb.Mvc/Models/Sync/ScoreData.cs
namespace OmniResources.FansOfFuryPublicWeb.Mvc.Models.Sync
{
    public class ScoreData
    {
        public string UserId { get; set; }

        public int Score { get; set; }
    }
}

OmniResources.FansOfFuryPublicWeb/OmniResources.FansOfFuryPublicWeb.Mvc/Controllers/BaseController.cs
using System.Web;
using System.Web.Mvc;

namespace OmniResources.FansOfFuryPublicWeb.Mvc.Controllers
{
    public class BaseController : Controller
    {
        private const string UserIdCookie = "FansOfFuryUserId";

        public string UserId
        {
            get
            {
                var cookie = Request.Cookies[UserIdCookie];
                return cookie == null ? null : cookie.Value;
            }

            set
            {
                Response.Cookies.Add(new HttpCookie(UserIdCookie, value));
            }
        }
    }
}

OmniResources.FansOfFuryPublicWeb/OmniResources.FansOfFuryPublicWeb.Mvc/Controllers/HomeController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using OmniResources.FansOfFuryPublicWeb.Data.Table.Repository;

namespace OmniResources.FansOfFuryPublicWeb.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly IUserDataRepository _userDataRepo;

        public HomeController(IUserDataRepository userDataRepo)
        {
            _userDataRepo = userDataRepo;
        }

        public async Task<ActionResult> Index()
        {
            return View((await _userDataRepo.Get()).OrderByDescending(x => x.Score).ToList());
        }
    }
}

OmniResources.FansOfFuryPublicWeb/OmniResources.FansOfFuryPublicWeb.Mvc/Controllers/QrCodeController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using OmniResources.FansOfFuryPublicWeb.Data.Table;
using OmniResources.FansOfFuryPublicWeb.Data.Table.Repository;
using OmniResources.FansOfFuryPublicWeb.Mvc.Models.QrCode;

namespace OmniResources.FansOfFuryPublicWeb.Mvc.Controllers
{
    public class QrCodeController : BaseController
    {
        private readonly IUserDataRepository _userDataRepo;
        private readonly ISurveyResponseRepository _surveyResponseRepo;

        public QrCodeController(IUserDataRepository userDataRepo, ISurveyResponseRepository surveyResponseRepo)
        {
            _userDataRepo = userDataRepo;
            _surveyResponseRepo = surveyResponseRepo;
        }

        [HttpGet]
        public async Task<ActionResult> Index(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return RedirectToAction("Index", "Home");

            UserId = id;

            var existingUser = await _userDataRepo.Get(id);

            var model = new SurveyResponseViewModel();

            if (existingUser != null)
                model.ScoreboardName = existingUser.ScoreboardName;

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Index(string id, SurveyResponseViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var existingUser = await _userDataRepo.Get(id);

            if (!string.IsNullOrEmpty(model.ScoreboardName))
            {
                existingUser = existingUser ?? new UserData();

                if (!string.IsNullOrWhiteSpace(existingUser.HashedPassword) && !BCrypt.Net.BCrypt.Verify(model.Password, existingUser.HashedPassword))
                {
                    ModelState.AddModelError("Password", "A username has already been set for this user, and the password you entered does not match.  Please try again.");
                    return View(model);
                }

                existingUser.ScoreboardName = model.ScoreboardName;
                existingUser.UserId = id;
                existingUser.HashedPassword = BCrypt.Net.BCrypt.HashPassword(model.Password);

                await _userDataRepo.Save(existingUser);
            }

            var surveyResponse = Mapper.Map<SurveyResponse>(model);
            surveyResponse.UserId = id;
            await _surveyResponseRepo.Save(surveyResponse);

            ViewData["Success"] = true;

            return View(model);
        }
    }
}

OmniResources.FansOfFuryPublicWeb/OmniResources.FansOfFuryPublicWeb.Mvc/Controllers/SyncApiController.cs
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Http;
using OmniResources.FansOfFuryPublicWeb.Data.Table;
using OmniResources.FansOfFuryPublicWeb.Data.Table.Repository;
using OmniResources.FansOfFuryPublicWeb.Mvc.Models.Sync;

namespace OmniResources.FansOfFuryPublicWeb.Mvc.Controllers
{
    public class SyncController : ApiController
    {
        private readonly IUserDataRepository _userDataRepo;

        public SyncController(IUserDataRepository userDataRepo)
        {
            _userDataRepo = userDataRepo;
        }

        public async Task<IEnumerable<UserData>> Post(IEnumerable<ScoreData> scores, string p)
        {
            if (p != ConfigurationManager.AppSettings["SyncPass"])
                return null;

            var users = (await _userDataRepo.Get()).ToDictionary(x => x.UserId, x => x);
            var usersToUpdate = new HashSet<UserData>();

            foreach (var score in scores)
            {
                UserData user;

                if (users.ContainsKey(score.UserId))
                {
                    user = users[score.UserId];
                }
                else
                {
                    user = new UserData { UserId = score.UserId };
                    users.Add(score.UserId, user);
                    usersToUpdate.Add(user);
                }

                if (user.Score != score.Score)
                {
                    user.Score = score.Score;
                    usersToUpdate.Add(user);
                }
            }

            if (usersToUpdate.Any())
                await _userDataRepo.SaveBatch(usersToUpdate);

            return users.Values;
        }
    }
}

OmniResources.FansOfFuryPublicWeb/OmniResources.FansOfFuryPublicWeb.Mvc/Views/Home/Index.cshtml
@model List<OmniResources.FansOfFuryPublicWeb.Data.Table.UserData>
@{
    ViewBag.Title = "Fans of Fury Scoreboard";
}

<div class="row">
    <img src="@Url.Content("~/Content/fof-scores.jpg")" class="img-responsive" alt="Fans of Fury High Scores">
</div>

@Html.Partial("_RelatedLinks", new ViewDataDictionary{ { "HideScoreboard", true } })

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Ranking</th>
                    <th>Username</th>
                    <th>Score</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Count; i++)
                {
                    <tr>
                        <td>@(i + 1)</td>
                        <td>@Model[i].DisplayScoreboardName()</td>
                        <td>@Model[i].Score</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

OmniResources.FansOfFuryPublicWeb/OmniResources.FansOfFuryPublicWeb.Mvc/Views/QrCode/Index.cshtml
@model OmniResources.FansOfFuryPublicWeb.Mvc.Models.QrCode.SurveyResponseViewModel
@{
    ViewBag.Title = "Fans of Fury Registration";
}

<div class="row">
    <img src="@Url.Content("~/Content/fof-game.jpg")" class="img-responsive" alt="Fans of Fury High Scores">
</div>

@Html.Partial("_RelatedLinks")

<div class="row">
    <div class="col-md-10 col-md-offset-1" style="padding-top:25px;">
        @if (!ViewContext.ViewData.ModelState.IsValid)
        {
            <div class="alert alert-danger" role="alert">
                @Html.ValidationSummary()
            </div>
        }
        @if (ViewData["Success"] != null)
        {
            <div class="alert alert-success" role="alert">
                Thanks for filling out the survey!  If you want to change your responses, feel free to do so below!
            </div>
        }

        @using (Html.BeginForm("Index", "QrCode", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="form-group">
                @Html.LabelFor(x => x.FirstName, new { @class = "col-sm-2 control-label" })
                <div class="col-sm-9">
                    @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.FirstName, null, new { @class = "help-block" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.LastName, new { @class = "col-sm-2 control-label" })
                <div class="col-sm-9">
                    @Html.TextBoxFor(x => x.LastName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.LastName, null, new { @class = "help-block" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.EmailAddress, new { @class = "col-sm-2 control-label" })
                <div class="col-sm-9">
                    @Html.TextBoxFor(x => x.EmailAddress, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.EmailAddress, null, new { @class = "help-block" })
                </div>
            </div>
            if (!string.IsNullOrWhiteSpace(Model.ScoreboardName))
            {
                <div class="form-group">
                    <label class="col-sm-2 control-label">Current Scoreboard Name</label>
                    <div class="col-sm-9">
                        <p class="form-control-static">@Model.ScoreboardName</p>
                    </div>
                </div>
            }

            <div class="form-group">
                @Html.LabelFor(x => x.ScoreboardName, new { @class = "col-sm-2 control-label" })
                <div class="col-sm-9">
                    @Html.TextBox("ScoreboardName", string.Empty, new { @class = "form-control", placeholder = "If you'd like your name to show on the scoreboard, enter it here!" })
                    @Html.ValidationMessageFor(x => x.ScoreboardName, null, new { @class = "help-block" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Password, new { @class = "col-sm-2 control-label" })
                <div class="col-sm-9">
                    @Html.PasswordFor(x => x.Password, new { @class = "form-control", placeholder = "If you enter a name for the scoreboard, you must enter a password." })
                    @Html.ValidationMessageFor(x => x.Password, null, new { @class = "help-block" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.ConfirmPassword, new { @class = "col-sm-2 control-label" })
                <div class="col-sm-9">
                    @Html.PasswordFor(x => x.ConfirmPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.ConfirmPassword, null, new { @class = "help-block" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-6">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            </div>
        }
    </div>
</div>

OmniResources.FansOfFuryPublicWeb/OmniResources.FansOfFuryPublicWeb.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Omni Resources, Inc.</title>
    <link href="//fonts.googleapis.com/css?family=Oswald:400,700,300" rel="stylesheet" type="text/css">
    <link href="//fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css">
    <link rel="icon" href="@Url.Content("~/Content/Site.css")" type="image/x-icon" />
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/"><img src="@Url.Content("~/Content/omni_logo_web1.png")" alt="Omni Resources" class="navbar-brand" style="padding:5px;margin-left:50px;" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav pull-right">
                    <li><a href="http://www.omniresources.com/about">ABOUT</a></li>
                    <li><a href="http://www.omniresources.com/expertise">EXPERTISE</a></li>
                    <li><a href="http://www.omniresources.com/our-process">PROCESS</a></li>
                    <li><a href="http://www.omniresources.com/our-portfolio">PORTFOLIO</a></li>
                    <li><a href="http://www.omniresources.com/careers">CAREERS</a></li>
                    <li><a href="http://www.omniresources.com/fans-of-fury">FANS OF FURY</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/libs")
    @Scripts.Render("~/bundles/app")
    @RenderSection("scripts", false)
</body>
</html>

OmniResources.FansOfFuryPublicWeb/OmniResources.FansOfFuryPublicWeb.Mvc/Views/Shared/_RelatedLinks.cshtml
<div class="row" style="background-color:#F4721A;">
    <div class="col-xs-12" style="text-align:right;font-size:18px;line-height:22px;padding:10px 40px;font-family:Oswald;font-weight:300;">
        <span style="color:#fff;">RELATED LINKS:</span>
        <a style="color:#3F3F3F;" href="http://www.omniresources.com/fans-of-fury-parts-list/">PARTS LIST</a> &middot;
        <a style="color:#3F3F3F;" href="http://www.omniresources.com/fans-of-fury-how-we-built-it/">HOW WE BUILT IT</a> &middot;
        <a style="color:#3F3F3F;" href="http://www.omniresources.com/mindfulness-meditation/">MEDITATION &amp; MINDFULNESS TIPS</a>
        @if (ViewData["HideScoreboard"] == null)
        {
            <text>&middot; <a style="color:#3F3F3F;" href="/">SCOREBOARD</a></text>
        }
    </div>
</div>